# Generated by Django 3.0.1 on 2020-01-01 22:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dlcm2', '0002_auto_20200101_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmed',
            name='med_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 1, 22, 41, 57, 368104, tzinfo=utc), verbose_name='Time of intake'),
        ),
    ]
