# Generated by Django 3.0.1 on 2020-01-02 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dlcm2', '0003_auto_20200101_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmed',
            name='med_dose',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dosage Taken'),
        ),
        migrations.AlterField(
            model_name='sectionmed',
            name='med_name',
            field=models.CharField(choices=[('OP', 'Olanzapine'), ('LP', 'Lorazepam')], max_length=2, verbose_name='Name of medicine'),
        ),
        migrations.AlterField(
            model_name='sectionmed',
            name='med_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 2, 9, 11, 24, 686979, tzinfo=utc), verbose_name='Time of intake'),
        ),
    ]
