# Generated by Django 3.0.1 on 2020-01-02 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dlcm2', '0004_auto_20200102_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmed',
            name='med_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 2, 15, 45, 25, 332429, tzinfo=utc), verbose_name='Time of intake'),
        ),
    ]
