# Generated by Django 3.0.1 on 2020-01-07 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dlcm2', '0006_auto_20200107_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmed',
            name='med_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 7, 20, 12, 37, 194133, tzinfo=utc), verbose_name='Time of intake'),
        ),
    ]
