# Generated by Django 3.0.1 on 2020-01-07 20:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dlcm2', '0008_auto_20200107_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_date', models.DateField(verbose_name='submission date')),
                ('med_time', models.TimeField(default=datetime.datetime(2020, 1, 7, 20, 35, 13, 181342, tzinfo=utc), verbose_name='Time of intake')),
                ('med_name', models.CharField(choices=[('OP', 'Olanzapine'), ('LP', 'Lorazepam')], max_length=2, verbose_name='Name of medicine')),
                ('med_dose', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dosage Taken')),
                ('med_dose_unit', models.CharField(choices=[('1', 'Milligram'), ('2', 'Gram'), ('3', 'Milliliter')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='SectionMed',
        ),
    ]
