# Generated by Django 3.0.1 on 2020-01-07 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dlcm2', '0009_auto_20200107_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinelog',
            options={'ordering': ['med_date', 'med_time']},
        ),
        migrations.AlterField(
            model_name='medicinelog',
            name='med_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 7, 21, 9, 41, 219853, tzinfo=utc), verbose_name='Time of intake'),
        ),
    ]
