# Generated by Django 3.0.1 on 2020-01-21 18:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Medication name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Medication units')),
            ],
        ),
        migrations.CreateModel(
            name='YesNoAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MedLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_time', models.DateTimeField(default=datetime.date.today, help_text='Enter date and time of intake')),
                ('med_dose', models.DecimalField(decimal_places=2, max_digits=6)),
                ('med_comment', models.CharField(blank=True, max_length=50)),
                ('med_dose_unit', models.ForeignKey(help_text='Choose dosage units', on_delete=django.db.models.deletion.CASCADE, to='dlcm3.Unit')),
                ('med_id', models.ForeignKey(help_text='Please select medication', on_delete=django.db.models.deletion.CASCADE, to='dlcm3.Medication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-med_time'],
                'permissions': (('can_enter_med_log', 'Enter med log entry'),),
            },
        ),
        migrations.CreateModel(
            name='MoodLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_date', models.DateField(default=datetime.date.today, help_text='Select Date')),
                ('other_symp', models.CharField(blank=True, max_length=300)),
                ('mood_score', models.IntegerField(help_text='Enter a score between 0 and 100')),
                ('msw_count', models.IntegerField(blank=True, null=True, verbose_name='Number of mood swings')),
                ('life_event', models.CharField(blank=True, max_length=50)),
                ('life_event_effect', models.IntegerField(blank=True, null=True, verbose_name='Effect of event on mood score between -4 and 4')),
                ('hosp_adm', models.BooleanField(blank=True, default=False, verbose_name='Admitted to hospital')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Enter your weight', max_digits=5, null=True)),
                ('sleep_hours', models.DecimalField(decimal_places=2, help_text='Enter hours slept', max_digits=4)),
                ('period', models.CharField(blank=True, max_length=5, null=True)),
                ('bp_phase', models.ForeignKey(default=5, help_text='Select bipolar phase', on_delete=django.db.models.deletion.CASCADE, to='dlcm3.Severity', verbose_name='Bipolar Phase')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mood_date'],
                'unique_together': {('user_id', 'mood_date')},
            },
        ),
    ]
