# Generated by Django 3.0.1 on 2020-01-24 18:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dlcm3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedLogEntry',
            new_name='MedLog',
        ),
        migrations.RenameModel(
            old_name='MoodLogEntry',
            new_name='MoodLog',
        ),
    ]
