# Generated by Django 3.0.1 on 2020-02-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlcm3', '0003_auto_20200127_0504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['name']},
        ),
    ]
